### ISSUE TITLE
ValueError: Input 0 of layer gru_cell_2 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

### ISSUE THREAD

**Issue by zhunipingan** [shentianxiao/language-style-transfer#31]
hi,
    I met the problem `ValueError: Input 0 of layer gru_cell_2 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.`
   Do you know how do solve it, I have no idea.

**Comment by zhunipingan** [comment]
solved it, maybe the version of tensorflow is not suited.

**Comment by zhufeijuanjuan** [comment]
i met the problem too. what's the suitable version of tf. thx.
