### ISSUE TITLE
How do you sample the result?

### ISSUE THREAD

**Issue by sheonhan** [shentianxiao/language-style-transfer#9]
[torch-rnn](https://github.com/jcjohnson/torch-rnn) seems to have a script that we can sample some results after training. Is there any way we can do the same thing here? 
If not, what would be the best way to go about doing it?

**Comment by shentianxiao** [comment]
There's an <code>online_testing</code> option. By running the command
```bash
python style_transfer.py --vocab ../model/yelp.vocab --model ../model/model --load_model true --online_testing true --beam 8
```
it will load a trained model, then you can input a style indicator and a sentence, and it will output the transferred sentence:
```bash
INFO:tensorflow:Restoring parameters from ../model/model
> 0 ok never going back to this place again .                 
original: just disappointed to go back this place again .
transfer: good place to go back again .
> 1 staff are very nice and efficient !
original: staff are very nice and efficient !
transfer: staff are very poor and was dead .
> exit
```
Is this what you are looking for?

**Comment by sheonhan** [comment]
This is it. Thanks!
